name: pyodb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.11.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hff52083_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=py310h06a4308_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - python=3.10.9=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyzmq=23.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.1=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - attrs==22.2.0
    - bleach==6.0.0
    - build==0.10.0
    - cachetools==5.3.0
    - certifi==2023.7.22
    - cffi==1.15.1
    - cfgv==3.3.1
    - chardet==5.1.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - colorama==0.4.6
    - coverage==7.2.2
    - cryptography==41.0.3
    - distlib==0.3.6
    - docutils==0.19
    - exceptiongroup==1.1.1
    - filelock==3.10.0
    - identify==2.5.21
    - idna==3.4
    - importlib-metadata==6.3.0
    - iniconfig==2.0.0
    - jaraco-classes==3.2.3
    - jeepney==0.8.0
    - jinja2==3.1.2
    - keyring==23.13.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - mdurl==0.1.2
    - memray==1.7.0
    - more-itertools==9.1.0
    - nodeenv==1.7.0
    - pdoc==13.0.0
    - pkginfo==1.9.6
    - pluggy==1.0.0
    - pre-commit==3.2.0
    - pycparser==2.21
    - pydantic==1.10.9
    - pyodb==0.1.1
    - pyproject-api==1.5.1
    - pyproject-hooks==1.0.0
    - pytest==7.2.2
    - pytest-cov==4.0.0
    - pyyaml==6.0
    - readme-renderer==37.3
    - requests==2.31.0
    - requests-toolbelt==0.10.1
    - rfc3986==2.0.0
    - rich==13.3.2
    - ruff==0.0.257
    - secretstorage==3.3.3
    - snakeviz==2.1.1
    - tornado==6.2
    - tox==4.4.8
    - tqdm==4.65.0
    - twine==4.0.2
    - urllib3==1.26.15
    - virtualenv==20.21.0
    - webencodings==0.5.1
    - zipp==3.15.0
prefix: /usr/miniconda3/envs/pyodb
